package inferencerdfs.gui;

import inferencerdfs.control.ModelLoaderSelector;
import inferencerdfs.control.ReasonerInference;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author D3str0y3r
 */
public class MainScreenContent extends javax.swing.JPanel {

    /**
     * Creates new form MainWindow
     */
    public MainScreenContent() {
        initComponents();
        fc = new JFileChooser();
        ri = new ReasonerInference();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formatButtonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        schemeLabel = new javax.swing.JLabel();
        schemeText = new javax.swing.JTextField();
        dataLabel = new javax.swing.JLabel();
        dataText = new javax.swing.JTextField();
        browseSchemeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        classesRadio = new javax.swing.JRadioButton();
        contraintsRadio = new javax.swing.JRadioButton();
        browseDataButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        resultConsole = new javax.swing.JScrollPane();
        consoleTextArea = new javax.swing.JTextArea();
        inferButton = new javax.swing.JButton();

        setNextFocusableComponent(browseSchemeButton);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        schemeLabel.setLabelFor(schemeText);
        schemeLabel.setText("Scheme : ");

        schemeText.setForeground(new java.awt.Color(153, 153, 153));
        schemeText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        schemeText.setToolTipText("Scheme file path");

        dataLabel.setText("Data : ");

        dataText.setForeground(new java.awt.Color(153, 153, 153));
        dataText.setToolTipText("Data path");
        dataText.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        browseSchemeButton.setText("Browse...");
        browseSchemeButton.setToolTipText("Browse scheme file");
        browseSchemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseSchemeButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        formatButtonGroup.add(classesRadio);
        classesRadio.setSelected(true);
        classesRadio.setText("Inferred classes");
        classesRadio.setToolTipText("");
        classesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classesRadioActionPerformed(evt);
            }
        });

        formatButtonGroup.add(contraintsRadio);
        contraintsRadio.setText("Contraint violations");
        contraintsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraintsRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contraintsRadio)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classesRadio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classesRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contraintsRadio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        browseDataButton.setText("Browse...");
        browseDataButton.setToolTipText("Browse data path");
        browseDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schemeLabel)
                    .addComponent(dataLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(schemeText, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addComponent(dataText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(browseSchemeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(browseDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(schemeLabel)
                            .addComponent(schemeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseSchemeButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataLabel)
                            .addComponent(dataText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseDataButton)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Console"));

        resultConsole.setBackground(new java.awt.Color(0, 0, 0));
        resultConsole.setToolTipText("Result console");
        resultConsole.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        resultConsole.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resultConsole.setEnabled(false);
        resultConsole.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N

        consoleTextArea.setEditable(false);
        consoleTextArea.setBackground(new java.awt.Color(51, 51, 51));
        consoleTextArea.setColumns(20);
        consoleTextArea.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        consoleTextArea.setForeground(new java.awt.Color(240, 240, 240));
        consoleTextArea.setLineWrap(true);
        consoleTextArea.setRows(5);
        consoleTextArea.setTabSize(4);
        consoleTextArea.setToolTipText("");
        resultConsole.setViewportView(consoleTextArea);

        inferButton.setText("Infer!");
        inferButton.setToolTipText("Infer data");
        inferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inferButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inferButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultConsole))
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultConsole, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inferButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inferButtonActionPerformed
        consoleTextArea.setText("========== START INFERENCE ==========\n\n");
        
        ri.makeInferences();
        
        if (classesRadio.isSelected()) {
            for (String clazz : ri.getInferredClasses()) {
                consoleTextArea.append(clazz + "\n");
            }
        }
        
        if (contraintsRadio.isSelected()) {
            for (String errors : ri.getContraintErrors()) {
                consoleTextArea.append(errors + "\n");
            }
        }
        
        consoleTextArea.append("\n========== END INFERENCE ==========");
    }//GEN-LAST:event_inferButtonActionPerformed

    private void classesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classesRadioActionPerformed
        consoleTextArea.setText("[+] Output : " + classesRadio.getText() + " selected!");
    }//GEN-LAST:event_classesRadioActionPerformed

    private void contraintsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraintsRadioActionPerformed
        consoleTextArea.setText("[+] Output : " + contraintsRadio.getText() + " selected!");
    }//GEN-LAST:event_contraintsRadioActionPerformed

    private void browseSchemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseSchemeButtonActionPerformed
        loadFile(schemeText, ModelLoaderSelector.SCHEME);
    }//GEN-LAST:event_browseSchemeButtonActionPerformed

    private void browseDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseDataButtonActionPerformed
        loadFile(dataText, ModelLoaderSelector.DATA);
    }//GEN-LAST:event_browseDataButtonActionPerformed

    private void loadFile(JTextField text, ModelLoaderSelector mls) {
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        String f = null;
        int val = fc.showOpenDialog(null);
        
        if (val == JFileChooser.APPROVE_OPTION) f = fc.getSelectedFile().getAbsolutePath();
        
        text.setText(f);
        
        if (f == null)
            consoleTextArea.setText("[!] Scheme could not be loaded!");
        else
            consoleTextArea.setText("[+] Scheme loaded at " 
                    + f);
        
        consoleTextArea.append("\n\n");
        
        ri.feedModel(mls, f);
    }

    private JFileChooser fc;
    private ReasonerInference ri;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseDataButton;
    private javax.swing.JButton browseSchemeButton;
    private javax.swing.JRadioButton classesRadio;
    private javax.swing.JTextArea consoleTextArea;
    private javax.swing.JRadioButton contraintsRadio;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JTextField dataText;
    private javax.swing.ButtonGroup formatButtonGroup;
    private javax.swing.JButton inferButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane resultConsole;
    private javax.swing.JLabel schemeLabel;
    private javax.swing.JTextField schemeText;
    // End of variables declaration//GEN-END:variables
}
