package gui;

import control.sparql.SPARQLQuery;
import control.sparql.enums.SPARQLFormatEnum;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author D3str0y3r
 */
public class MainScreenContent extends javax.swing.JPanel {

    /**
     * Creates new form MainWindow
     */
    public MainScreenContent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formatButtonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rdLabel = new javax.swing.JLabel();
        rdfText = new javax.swing.JTextField();
        urlLabel = new javax.swing.JLabel();
        urlText = new javax.swing.JTextField();
        rdfButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtFileRadio = new javax.swing.JRadioButton();
        srxFileRadio = new javax.swing.JRadioButton();
        queryPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryArea = new javax.swing.JTextArea();
        queryButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        resultConsole = new javax.swing.JScrollPane();
        consoleTextArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();

        setNextFocusableComponent(rdfButton);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Data source"));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        rdLabel.setLabelFor(rdfText);
        rdLabel.setText("RDF File  : ");

        rdfText.setForeground(new java.awt.Color(153, 153, 153));
        rdfText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        rdfText.setToolTipText("RDF file path");
        rdfText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rdfTextKeyTyped(evt);
            }
        });

        urlLabel.setText("URL : ");

        urlText.setForeground(new java.awt.Color(153, 153, 153));
        urlText.setToolTipText("URL data source");
        urlText.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        urlText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                urlTextKeyTyped(evt);
            }
        });

        rdfButton.setText("Browse...");
        rdfButton.setToolTipText("Browse scheme file");
        rdfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdfButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Output format"));

        formatButtonGroup.add(txtFileRadio);
        txtFileRadio.setSelected(true);
        txtFileRadio.setText("TXT File");
        txtFileRadio.setToolTipText("Save SPARQL result in text file format");
        txtFileRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileRadioActionPerformed(evt);
            }
        });

        formatButtonGroup.add(srxFileRadio);
        srxFileRadio.setText("SRX File");
        srxFileRadio.setToolTipText("Save SPARQL result in SRX file format");
        srxFileRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srxFileRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFileRadio)
                    .addComponent(srxFileRadio))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFileRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(srxFileRadio)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdLabel)
                    .addComponent(urlLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdfText, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                    .addComponent(urlText))
                .addGap(18, 18, 18)
                .addComponent(rdfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdLabel)
                            .addComponent(rdfText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdfButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urlText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urlLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        queryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Query"));

        queryArea.setColumns(20);
        queryArea.setRows(5);
        queryArea.setToolTipText("Write here your SPARQL query");
        jScrollPane1.setViewportView(queryArea);

        queryButton.setText("Query");
        queryButton.setToolTipText("Execute SPARQL query");
        queryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout queryPanelLayout = new javax.swing.GroupLayout(queryPanel);
        queryPanel.setLayout(queryPanelLayout);
        queryPanelLayout.setHorizontalGroup(
            queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(queryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        queryPanelLayout.setVerticalGroup(
            queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queryButton)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Console"));

        resultConsole.setBackground(new java.awt.Color(0, 0, 0));
        resultConsole.setToolTipText("Result console");
        resultConsole.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        resultConsole.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resultConsole.setEnabled(false);
        resultConsole.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N

        consoleTextArea.setEditable(false);
        consoleTextArea.setBackground(new java.awt.Color(51, 51, 51));
        consoleTextArea.setColumns(20);
        consoleTextArea.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        consoleTextArea.setForeground(new java.awt.Color(240, 240, 240));
        consoleTextArea.setLineWrap(true);
        consoleTextArea.setRows(5);
        consoleTextArea.setTabSize(4);
        consoleTextArea.setToolTipText("");
        resultConsole.setViewportView(consoleTextArea);

        saveButton.setText("Save");
        saveButton.setToolTipText("Save query");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(resultConsole)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(queryPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String path = chooseSavePath();
        SPARQLQuery.saveToFile(path);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void queryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryButtonActionPerformed
        if (!queryArea.getText().equals("")) {
            String result = "";
            
            if (!rdfText.getText().equals("") && rdfText.isEnabled()) 
                result = SPARQLQuery.executeLocalQuery(rdfText.getText(), queryArea.getText(), sfe);
            else if (!urlText.getText().equals("") && urlText.isEnabled())
                result = SPARQLQuery.executeRemoteQuery(urlText.getText(), queryArea.getText(), sfe);
            else {
                consoleTextArea.setText("[!] Error: Introduce an URL/path to query");
                return;
            }
        
            consoleTextArea.setText(result);
        } else {
            consoleTextArea.setText("[!] Error: Insert a query to execute");
        }
    }//GEN-LAST:event_queryButtonActionPerformed

    private void srxFileRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srxFileRadioActionPerformed
        consoleTextArea.setText("[+] Output : " + srxFileRadio.getText().replace("File", "format") + " selected!");
        sfe = SPARQLFormatEnum.SRX;
    }//GEN-LAST:event_srxFileRadioActionPerformed

    private void txtFileRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileRadioActionPerformed
        consoleTextArea.setText("[+] Output : " + txtFileRadio.getText().replace("File", "format") + " selected!");
        sfe =SPARQLFormatEnum.TXT;
    }//GEN-LAST:event_txtFileRadioActionPerformed

    private void rdfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdfButtonActionPerformed
        loadFile(rdfText);
        
        if (!rdfText.getText().equals("")) 
            urlText.setEnabled(false);
        else
            urlText.setEnabled(true);
    }//GEN-LAST:event_rdfButtonActionPerformed

    private void urlTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_urlTextKeyTyped
        if(!urlText.getText().equals(""))
            rdfText.setEnabled(false);
        else
            rdfText.setEnabled(true);
    }//GEN-LAST:event_urlTextKeyTyped

    private void rdfTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdfTextKeyTyped
        if (!rdfText.getText().equals("")) 
            urlText.setEnabled(false);
        else
            urlText.setEnabled(true);
    }//GEN-LAST:event_rdfTextKeyTyped

    private String chooseSavePath() {
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setCurrentDirectory(new java.io.File("."));
        
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Text File", "txt"));
        fc.addChoosableFileFilter(new FileNameExtensionFilter("SPARQL Query Results XML File", "srx"));
        
        String f = "";
        int val = fc.showSaveDialog(null);
        
        if (val == JFileChooser.APPROVE_OPTION) f = fc.getSelectedFile().getAbsolutePath();
    
        if (txtFileRadio.isSelected()) {
            consoleTextArea.setText("[+] SPARQL result saved in " + txtFileRadio.getText().replace("File", "format"));
            if (!f.contains(".txt")) f += ".txt";
        } else if (srxFileRadio.isSelected()) {
            consoleTextArea.setText("[+] SPARQL result saved in " + srxFileRadio.getText().replace("File", "format"));
            if (!f.contains(".srx")) f += ".srx";
        }
        
        System.out.println(f);
        return f;            
    }
    
    private void loadFile(JTextField text) {
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setCurrentDirectory(new java.io.File("."));
        
        fc.addChoosableFileFilter(new FileNameExtensionFilter("XML/RDF File", "rdf"));
        fc.addChoosableFileFilter(new FileNameExtensionFilter("TURTLE File", "ttl"));
        
        String f = null;
        int val = fc.showOpenDialog(null);
        
        if (val == JFileChooser.APPROVE_OPTION) f = fc.getSelectedFile().getAbsolutePath();
        
        text.setText(f);
        
        if (f == null)
            consoleTextArea.setText("[!] RDF file could not be loaded!");
        else
            consoleTextArea.setText("[+] RDF file loaded : " 
                    + f);
        
        consoleTextArea.append("\n\n");
    }

    private SPARQLFormatEnum sfe = SPARQLFormatEnum.TXT;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea consoleTextArea;
    private javax.swing.ButtonGroup formatButtonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea queryArea;
    private javax.swing.JButton queryButton;
    private javax.swing.JPanel queryPanel;
    private javax.swing.JLabel rdLabel;
    private javax.swing.JButton rdfButton;
    private javax.swing.JTextField rdfText;
    private javax.swing.JScrollPane resultConsole;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton srxFileRadio;
    private javax.swing.JRadioButton txtFileRadio;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField urlText;
    // End of variables declaration//GEN-END:variables
}
